name: Browser port

on:
  push:
    branches:
      - web-port
  workflow_dispatch:

jobs:
  compile-browser-host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Compile .NET 8 browser framework
        run: dotnet build osu.Framework/osu.Framework.csproj --configuration Release -p:OsuBrowserBuild=true
