name: Browser port

on:
  push:
    branches:
      - web-port
  workflow_dispatch:

jobs:
  compile-browser-host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Compile framework with browser host
        run: dotnet build osu.Framework/osu.Framework.csproj --configuration Release --no-restore

      - name: Restore if cache is cold
        if: failure()
        run: dotnet build osu.Framework/osu.Framework.csproj --configuration Release
